services:
  backend:
    image: ghcr.io/antonsplavnik/transcendence:latest
    ports:
      - "80:8080"
      - "443:8443/tcp"
      - "443:8443/udp"
    volumes:
      - db-data:/app/data
      - acme-cache:/app/acme
      - ./prod_config.toml:/app/config.toml:ro
    env_file: .env
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 120
      WATCHTOWER_CLEANUP: "true"
    restart: unless-stopped

volumes:
  db-data:
  acme-cache:
